version: "3.7"

services:
  frontend:
    build:
      context: ./feapp
    container_name: frontend
    # command: npm run dev
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./feapp:/app
    ports:
      # // if we remove this port than we can only accesss these container via nginx and not directly
      - "3000:3000"

  api:
    build:
      context: ./api
    container_name: api
    tty: true
    restart: always
    # command: run start
    init: true
    environment:
      - PORT=3001
      - URL="http://localhost"
      - MONGO_URL=mongodb://db_mongo:27017
      - CHOKIDAR_USEPOLLING=true
      - API_VERSION=v1
    volumes:
      - ./api/src:/app/src
    ports:
      #Will map the container port 8000 to the host server port 8000.
      - "3001:3001"

  db_mongo:
    image: mongo
    restart: always
    container_name: db_mongo
    volumes:
      - mongodb_api:/data/db
    ports:
      - "27017:27017"

  nginx:
    image: nginx:1.21.4-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  mongodb_api:
